[package]
name = "slang"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
slang-sys = { path = "slang-sys" }

[workspace]
members = ["slang-sys"]

[features]
from-source = ["slang-sys/from-source"]
