[package]
name = "slang-sys"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
build = "build.rs"

[build-dependencies]
anyhow = "1"
bindgen = "0.71"
cmake = { version = "0.1", optional = true }

[features]
from-source = ["dep:cmake"]
